### ISSUE TITLE
Once again

### ISSUE THREAD

**Issue by Monokiro** [hachchch/-GeneCiv-#11]
java.lang.Exception: Unit Eukaryote of Ediacara at Tile @(49.0,27.0), Snow, {2} {Aluminum} can't be put in tile Tile @(47.0,27.0), Tundra, Eumycetozoa - Ediacara!
	at com.unciv.logic.map.mapunit.MapUnit.putInTile(MapUnit.kt:850)

**Comment by hachchch** [comment]
ok I will work on it.

**Comment by Monokiro** [comment]
New civs testing, especially interesting Vaalbara
