### ISSUE TITLE
Fog disappearing 

### ISSUE THREAD

**Issue by SchoeniosX** [hachchch/-GeneCiv-#12]
Fog doesn't disappear by discovering the area.

**Comment by hachchch** [comment]
That's intentional.
All cells and Organic Compounds have No Sight (hidden from users).

**Comment by SchoeniosX** [comment]
> That's intentional. All cells and Organic Compounds have No Sight.

One another thing is, that the Natural wonders are not shown. They remain invisible.

**Comment by hachchch** [comment]
well, it seems bug.
Thanks to notice that!
I will be fix it later

> > That's intentional. All cells and Organic Compounds have No Sight.
> 
> One another thing is, that the Natural wonders are not shown. They remain invisible.

**Comment by Monokiro** [comment]
> That's intentional. All cells and Organic Compounds have No Sight.

Well actually now AIs do have sight with cells or compounds to prevent crash, right?

**Comment by hachchch** [comment]
yeah right.
When the AI ​​starts retreating,
an error occurs because the enemy is not visible for cells. maybe

**Comment by hachchch** [comment]
The players have to wandering undiscoverable land to settling new city on Hadean to Paleoproterozoic
However, I don't plan giving any eyesight to Human player's Settler.
because it will be very funny and ridiculous.

**Comment by SchoeniosX** [comment]
Works 💪✅
