### ISSUE TITLE
Invisible Wonder

### ISSUE THREAD

**Issue by SchoeniosX** [hachchch/-GeneCiv-#14]
The miracle “continental shelf” cannot be seen in the editor, nor is the icon visible

**Comment by hachchch** [comment]
Ah...that's a my code miss.
thanks to notice me that, I'll fix it right now!

**Comment by SchoeniosX** [comment]
It works but the texture has changed for the ocean. “Light” became “dark”.

![Screenshot_20240212-153411_Unciv](https://github.com/hachchch/-GeneCiv-/assets/148587231/18b3b8f2-360b-4751-80af-4a5c744b7a6b)

Changed to:

![Screenshot_20240212-153343_Unciv](https://github.com/hachchch/-GeneCiv-/assets/148587231/28665c35-7626-4e45-92bc-ca2a2a3ce801)

**Comment by hachchch** [comment]
it fine. i did make ocean darker

**Comment by hachchch** [comment]
![Screenshot 2024-02-12 23 43 40](https://github.com/hachchch/-GeneCiv-/assets/137990341/dc2c6428-50bb-43d2-9953-821f11ad12e0)

![Screenshot 2024-02-12 23 43 16](https://github.com/hachchch/-GeneCiv-/assets/137990341/3c5f6555-1c59-4b7e-a61f-be6afde7f44c)

it looks better, isn't it?
